### ISSUE TITLE
Passing strings with spaces as arguments to include  does not work

### ISSUE THREAD

**Issue by zeewolfik** [eskypl/glide-templates#10]
Given *{expression}* is any valid JS expression according to documentation, 
```javascript
{include template=views/items-list items=$tpl.data class='text-red bg-white'}
```
should pass **class** variable correctly, but instead it gets split in the middle (on space char).

**Comment by kwiniarski** [comment]
Fixed with commit https://github.com/eskypl/glide-templates/commit/22c4d8c3185d44b0e5dcdf421702239ec9973e63
