### ISSUE TITLE
Optimizer does not include templates embedded using {include ...} in compiled package

### ISSUE THREAD

**Issue by zeewolfik** [eskypl/glide-templates#8]
[main.tpl]
```javascript
{include template=components/flights/flight-offer/views/price}
```

Because build file does not contain this template (**it should**), requirejs tries to fetch missing template but fails (tries to download */components/flights/flight-offer/views/price.js*).

**Comment by kwiniarski** [comment]
This bug is not present in current version. It was true for 1.1.0, where amdclean process was removing `require` statement from `build.js`. In result none of included templates was present in generated bundle.
